In [5]:


#%% import libraries
import datetime
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [6]:

#%% sheet id is the long string of numbers and letters insie the http link:
# pan between multiple links by commenting out a line with a #
#sheet_id'1b5hBs7-Ao8MCEC4_KznmJaPvTyYeivmO-V9mWrjUp04'

sheet_id = '1g1t7XujC5If_AGhmw7cfe0PHMfvdhf0NpjmRBZG1vy8'

#sheet_id = '16acnfMeLW7e_w1nJVtCNOc-Xq3FjS2CgxZS7gGu_zN4'
df = pd.read_csv(f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv")

In [ ]:
#%% assign column names within df, remove first row, 
#  convert object to int, delete unneeded columns
df.columns = ['delete1','contact_ID', 'project_id','project_name','company',
              'contact_website','email','address','full_name','phone_number',
              'alt_phone','result_count','lead_status','call_date_time',
              'user_name','comment','call_hist','iss_details'
              ]
df = df.iloc[1:]

del df['delete1']
del df['contact_ID']
del df['project_id']
del df['contact_website']
del df['alt_phone']
del df['iss_details']

In [8]:
#%%
df0 = df.drop_duplicates(subset=['full_name','phone_number'],keep='last')

In [9]:
print(df())

TypeError: 'DataFrame' object is not callable

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 788 entries, 1 to 788
Data columns (total 12 columns):
project_name      788 non-null object
company           788 non-null object
email             771 non-null object
address           0 non-null float64
full_name         788 non-null object
phone_number      788 non-null int64
result_count      788 non-null int64
lead_status       788 non-null object
call_date_time    788 non-null object
user_name         788 non-null object
comment           788 non-null object
call_hist         788 non-null object
dtypes: float64(1), int64(2), object(9)
memory usage: 74.0+ KB